services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "1100:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: 